/**
 * FileCard — Manus-style file attachment card for chat messages.
 * Shows file icon (by type), name, size, and download/preview button.
 * Supports in-app preview for CSV, DOCX, MD, TXT, JSON, and code files.
 */

import { useState, useCallback } from 'react';
import { useTheme } from '../context/ThemeContext';
import { saveAs } from 'file-saver';

// ── File type icon + color mapping ──────────────────────────────────────────

interface FileTypeConfig {
  icon: string;       // Short label inside the icon badge
  color: string;      // Background color
  textColor: string;  // Text color for the icon
}

function getFileTypeConfig(filename: string): FileTypeConfig {
  const ext = filename.split('.').pop()?.toLowerCase() || '';
  switch (ext) {
    case 'docx': case 'doc':
      return { icon: 'IMG:/icons/ui/docx.png', color: '#4285F4', textColor: '#fff' };
    case 'pdf':
      return { icon: 'PDF', color: '#EA4335', textColor: '#fff' };
    case 'xlsx': case 'xls': case 'csv':
      return { icon: 'X', color: '#0F9D58', textColor: '#fff' };
    case 'pptx': case 'ppt':
      return { icon: 'P', color: '#FF6D01', textColor: '#fff' };
    case 'py': case 'js': case 'ts': case 'tsx': case 'jsx':
      return { icon: '</>', color: '#1a1a2e', textColor: '#e0e0e0' };
    case 'json':
      return { icon: '{ }', color: '#1a1a2e', textColor: '#fbbf24' };
    case 'html': case 'css':
      return { icon: '<>', color: '#e34c26', textColor: '#fff' };
    case 'md': case 'txt':
      return { icon: '≡', color: '#6366f1', textColor: '#fff' };
    case 'png': case 'jpg': case 'jpeg': case 'gif': case 'svg': case 'webp':
      return { icon: '◻', color: '#8b5cf6', textColor: '#fff' };
    case 'zip': case 'tar': case 'gz':
      return { icon: '◆', color: '#78716c', textColor: '#fff' };
    default:
      return { icon: '◇', color: '#6b7280', textColor: '#fff' };
  }
}

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

// ── FileCard ────────────────────────────────────────────────────────────────

export interface FileAttachment {
  id: string;
  filename: string;
  sizeBytes: number;
  blob?: Blob;
  dataUrl?: string;
  createdAt: number;
}

interface FileCardProps {
  file: FileAttachment;
}

// Check if a file type supports in-app preview
function isPreviewable(filename: string): boolean {
  const ext = filename.split('.').pop()?.toLowerCase() || '';
  return ['csv', 'tsv', 'txt', 'md', 'json', 'py', 'js', 'ts', 'tsx', 'jsx', 'html', 'css', 'sh', 'yaml', 'yml', 'xml', 'docx'].includes(ext);
}

// Parse CSV into rows (handles quoted fields)
function parseCSV(text: string): string[][] {
  const rows: string[][] = [];
  const lines = text.split('\n');
  for (const line of lines) {
    if (!line.trim()) continue;
    // Simple CSV parser — handles quoted fields with commas
    const cells: string[] = [];
    let current = '';
    let inQuotes = false;
    for (let i = 0; i < line.length; i++) {
      if (line[i] === '"') { inQuotes = !inQuotes; continue; }
      if (line[i] === ',' && !inQuotes) { cells.push(current.trim()); current = ''; continue; }
      current += line[i];
    }
    cells.push(current.trim());
    rows.push(cells);
  }
  return rows;
}

// ── FilePreviewModal ──────────────────────────────────────────────────────────

function FilePreviewModal({ file, onClose }: { file: FileAttachment; onClose: () => void }) {
  const { isDarkMode } = useTheme();
  const [content, setContent] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const ext = file.filename.split('.').pop()?.toLowerCase() || '';

  // Load content on mount
  useState(() => {
    if (!file.blob) { setLoading(false); return; }
    if (ext === 'docx') {
      // For DOCX, extract text using docx library or show raw XML
      file.blob.text().then(t => {
        // DOCX is a zip — show a styled preview message
        setContent('[DOCX Preview]\n\nThis document was generated by Neuro. Click "Download" to open in Word/Google Docs.\n\nFile size: ' + formatSize(file.sizeBytes));
        setLoading(false);
      }).catch(() => { setLoading(false); });
    } else {
      file.blob.text().then(t => { setContent(t); setLoading(false); }).catch(() => { setLoading(false); });
    }
  });

  const isCSV = ext === 'csv' || ext === 'tsv';
  const csvRows = isCSV && content ? parseCSV(content) : null;

  const handleDownload = () => {
    if (file.blob) saveAs(file.blob, file.filename);
  };

  return (
    <div
      onClick={onClose}
      style={{
        position: 'fixed', inset: 0, zIndex: 9999,
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        background: 'rgba(0,0,0,0.72)', backdropFilter: 'blur(6px)',
      }}
    >
      <div
        onClick={e => e.stopPropagation()}
        style={{
          background: isDarkMode ? 'rgb(18,18,26)' : '#fff',
          borderRadius: 16, padding: 0, maxWidth: 700, width: '92%',
          maxHeight: '80vh', display: 'flex', flexDirection: 'column',
          border: `1px solid ${isDarkMode ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.08)'}`,
          boxShadow: '0 24px 64px rgba(0,0,0,0.5)',
          overflow: 'hidden',
        }}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-3.5" style={{ borderBottom: `1px solid ${isDarkMode ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.06)'}` }}>
          <span style={{ fontSize: 14, fontWeight: 600, color: isDarkMode ? 'rgba(255,255,255,0.85)' : '#1a1a1a', fontFamily: "'ABC Diatype Plus', system-ui, sans-serif" }}>
            {file.filename}
          </span>
          <div className="flex items-center gap-2">
            <button onClick={handleDownload} title="Download" style={{ padding: '4px 10px', borderRadius: 6, fontSize: 11, fontWeight: 500, background: isDarkMode ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.05)', color: isDarkMode ? 'rgba(255,255,255,0.6)' : '#666', border: 'none', cursor: 'pointer' }}>
              ↓ Download
            </button>
            <button onClick={onClose} style={{ color: isDarkMode ? 'rgba(255,255,255,0.4)' : '#999', padding: 4, cursor: 'pointer', background: 'none', border: 'none' }}>
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><line x1="18" y1="6" x2="6" y2="18" /><line x1="6" y1="6" x2="18" y2="18" /></svg>
            </button>
          </div>
        </div>

        {/* Content */}
        <div style={{ flex: 1, overflow: 'auto', padding: isCSV ? 0 : '16px 20px' }}>
          {loading ? (
            <div style={{ color: isDarkMode ? 'rgba(255,255,255,0.3)' : '#999', fontSize: 13, padding: 20 }}>Loading...</div>
          ) : csvRows && csvRows.length > 0 ? (
            <div style={{ overflow: 'auto' }}>
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 12, fontFamily: "'ABC Diatype Plus', monospace" }}>
                <thead>
                  <tr>
                    {csvRows[0].map((cell, i) => (
                      <th key={i} style={{
                        padding: '8px 12px', textAlign: 'left', fontWeight: 600,
                        borderBottom: `2px solid ${isDarkMode ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.1)'}`,
                        color: isDarkMode ? 'rgba(255,255,255,0.7)' : '#333',
                        position: 'sticky', top: 0,
                        background: isDarkMode ? 'rgb(18,18,26)' : '#fff',
                      }}>
                        {cell}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {csvRows.slice(1).map((row, ri) => (
                    <tr key={ri} style={{ background: ri % 2 === 0 ? 'transparent' : (isDarkMode ? 'rgba(255,255,255,0.02)' : 'rgba(0,0,0,0.02)') }}>
                      {row.map((cell, ci) => (
                        <td key={ci} style={{
                          padding: '6px 12px',
                          borderBottom: `1px solid ${isDarkMode ? 'rgba(255,255,255,0.04)' : 'rgba(0,0,0,0.04)'}`,
                          color: isDarkMode ? 'rgba(255,255,255,0.6)' : '#555',
                        }}>
                          {cell}
                        </td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : content ? (
            <pre style={{
              fontSize: 12, lineHeight: 1.6, whiteSpace: 'pre-wrap', wordBreak: 'break-word',
              color: isDarkMode ? 'rgba(255,255,255,0.7)' : '#333',
              fontFamily: ext === 'md' || ext === 'txt' ? "'ABC Diatype Plus', system-ui, sans-serif" : "'SF Mono', 'Fira Code', monospace",
              margin: 0,
            }}>
              {content}
            </pre>
          ) : (
            <div style={{ color: isDarkMode ? 'rgba(255,255,255,0.3)' : '#999', fontSize: 13 }}>Unable to preview this file.</div>
          )}
        </div>
      </div>
    </div>
  );
}

export function FileCard({ file }: FileCardProps) {
  const { isDarkMode } = useTheme();
  const [showPreview, setShowPreview] = useState(false);
  const config = getFileTypeConfig(file.filename);
  const ext = file.filename.split('.').pop()?.toUpperCase() || 'FILE';
  const canPreview = isPreviewable(file.filename);

  const handleDownload = useCallback(() => {
    if (file.blob) {
      saveAs(file.blob, file.filename);
    } else if (file.dataUrl) {
      fetch(file.dataUrl)
        .then(r => r.blob())
        .then(blob => saveAs(blob, file.filename));
    }
  }, [file]);

  const handleClick = () => {
    if (canPreview) {
      setShowPreview(true);
    } else {
      handleDownload();
    }
  };

  return (
    <>
    {showPreview && <FilePreviewModal file={file} onClose={() => setShowPreview(false)} />}
    <div
      onClick={handleClick}
      className="flex items-center gap-3 cursor-pointer transition-all hover:scale-[1.01]"
      style={{
        padding: '12px 14px',
        borderRadius: 12,
        background: isDarkMode ? 'rgba(255,255,255,0.04)' : 'rgba(0,0,0,0.03)',
        border: `1px solid ${isDarkMode ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.06)'}`,
        maxWidth: 320,
      }}
    >
      {/* File type icon badge */}
      <div
        className="shrink-0 flex items-center justify-center rounded-lg"
        style={{
          width: 40,
          height: 40,
          background: config.icon.startsWith('IMG:') ? 'transparent' : config.color,
          color: config.textColor,
          fontSize: config.icon.length > 2 ? 10 : 14,
          fontWeight: 700,
          fontFamily: "'ABC Diatype Plus', system-ui, sans-serif",
          letterSpacing: '-0.02em',
        }}
      >
        {config.icon.startsWith('IMG:') ? (
          <img src={config.icon.slice(4)} alt="" style={{ width: 32, height: 32, borderRadius: 4 }} />
        ) : config.icon}
      </div>

      {/* File info */}
      <div className="flex-1 min-w-0">
        <div
          className="truncate"
          style={{
            fontSize: 13,
            fontWeight: 500,
            color: isDarkMode ? 'rgba(255,255,255,0.85)' : '#1a1a1a',
            fontFamily: "'ABC Diatype Plus', system-ui, sans-serif",
          }}
        >
          {file.filename}
        </div>
        <div
          style={{
            fontSize: 11,
            color: isDarkMode ? 'rgba(255,255,255,0.35)' : '#999',
            marginTop: 2,
          }}
        >
          {ext} Document · {formatSize(file.sizeBytes)}{canPreview ? ' · Click to preview' : ''}
        </div>
      </div>

      {/* Download button (separate from preview click) */}
      <button
        onClick={(e) => { e.stopPropagation(); handleDownload(); }}
        title="Download"
        className="shrink-0"
        style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 4 }}
      >
        <svg
          width="16" height="16" viewBox="0 0 24 24" fill="none"
          stroke={isDarkMode ? 'rgba(255,255,255,0.3)' : 'rgba(0,0,0,0.3)'}
          strokeWidth="2" strokeLinecap="round"
        >
          <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4" />
          <polyline points="7 10 12 15 17 10" />
          <line x1="12" y1="15" x2="12" y2="3" />
        </svg>
      </button>
    </div>
    </>
  );
}

// ── FilesPanel — "All files in this task" modal ─────────────────────────────

type FileFilter = 'all' | 'documents' | 'images' | 'code' | 'links';

interface FilesPanelProps {
  files: FileAttachment[];
  onClose: () => void;
}

export function FilesPanel({ files, onClose }: FilesPanelProps) {
  const { isDarkMode } = useTheme();
  const [filter, setFilter] = useState<FileFilter>('all');

  const filtered = files.filter(f => {
    if (filter === 'all') return true;
    const ext = f.filename.split('.').pop()?.toLowerCase() || '';
    if (filter === 'documents') return ['docx', 'doc', 'pdf', 'txt', 'md', 'xlsx', 'pptx'].includes(ext);
    if (filter === 'images') return ['png', 'jpg', 'jpeg', 'gif', 'svg', 'webp'].includes(ext);
    if (filter === 'code') return ['py', 'js', 'ts', 'tsx', 'jsx', 'json', 'html', 'css', 'sh'].includes(ext);
    return true;
  });

  const tabs: { key: FileFilter; label: string }[] = [
    { key: 'all', label: 'All' },
    { key: 'documents', label: 'Documents' },
    { key: 'images', label: 'Images' },
    { key: 'code', label: 'Code files' },
  ];

  return (
    <div
      style={{
        background: isDarkMode ? 'rgba(18,18,24,0.98)' : 'rgba(255,255,255,0.98)',
        borderRadius: 16,
        padding: '20px 24px',
        maxWidth: 480,
        width: '100%',
        border: `1px solid ${isDarkMode ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.08)'}`,
        boxShadow: '0 16px 48px rgba(0,0,0,0.3)',
      }}
    >
      {/* Header */}
      <div className="flex items-center justify-between mb-4">
        <span style={{
          fontSize: 16,
          fontWeight: 600,
          color: isDarkMode ? 'rgba(255,255,255,0.85)' : '#1a1a1a',
          fontFamily: "'ABC Diatype Plus', system-ui, sans-serif",
        }}>
          All files in this task
        </span>
        <button onClick={onClose} style={{ color: isDarkMode ? 'rgba(255,255,255,0.4)' : '#999' }}>
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round">
            <line x1="18" y1="6" x2="6" y2="18" /><line x1="6" y1="6" x2="18" y2="18" />
          </svg>
        </button>
      </div>

      {/* Filter tabs */}
      <div className="flex gap-2 mb-4 flex-wrap">
        {tabs.map(tab => (
          <button
            key={tab.key}
            onClick={() => setFilter(tab.key)}
            style={{
              padding: '5px 12px',
              borderRadius: 20,
              fontSize: 12,
              fontWeight: 500,
              fontFamily: "'ABC Diatype Plus', system-ui, sans-serif",
              background: filter === tab.key
                ? (isDarkMode ? 'rgba(255,255,255,0.12)' : 'rgba(0,0,0,0.08)')
                : 'transparent',
              color: filter === tab.key
                ? (isDarkMode ? 'rgba(255,255,255,0.85)' : '#1a1a1a')
                : (isDarkMode ? 'rgba(255,255,255,0.4)' : '#999'),
              border: `1px solid ${filter === tab.key
                ? (isDarkMode ? 'rgba(255,255,255,0.15)' : 'rgba(0,0,0,0.12)')
                : 'transparent'}`,
            }}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* File list */}
      <div className="flex flex-col gap-2" style={{ maxHeight: 400, overflowY: 'auto' }}>
        {filtered.length === 0 ? (
          <div style={{ fontSize: 13, color: isDarkMode ? 'rgba(255,255,255,0.3)' : '#999', textAlign: 'center', padding: 20 }}>
            No files yet
          </div>
        ) : (
          filtered.map(f => <FileCard key={f.id} file={f} />)
        )}
      </div>
    </div>
  );
}
