/**
 * Document Renderer — Convert various formats to displayable content
 *
 * Handles:
 * - DOCX → Markdown conversion
 * - PDF → Preview + text extraction
 * - HTML → Safe sanitization
 * - Markdown → As-is (react-markdown handles rendering)
 * - Code → With language detection
 * - Plain text → As-is
 */

/**
 * Detect file type from filename or MIME type
 */
export function detectFileType(filename: string): 'docx' | 'pdf' | 'md' | 'html' | 'txt' | 'code' {
  if (!filename) return 'txt';

  const ext = filename.split('.').pop()?.toLowerCase() || '';

  const codeExtensions = ['py', 'js', 'ts', 'tsx', 'jsx', 'java', 'cpp', 'c', 'cs', 'go', 'rs', 'rb', 'php', 'swift', 'kt', 'scala', 'sql', 'sh', 'bash', 'json', 'yaml', 'yml', 'xml', 'css', 'scss', 'html'];

  switch (ext) {
    case 'docx':
      return 'docx';
    case 'pdf':
      return 'pdf';
    case 'md':
    case 'markdown':
      return 'md';
    case 'html':
    case 'htm':
      return 'html';
    case 'txt':
    case 'text':
      return 'txt';
    default:
      return codeExtensions.includes(ext) ? 'code' : 'txt';
  }
}

/**
 * Detect programming language from file extension
 */
export function detectLanguage(filename: string): string {
  const ext = filename.split('.').pop()?.toLowerCase() || '';

  const langMap: Record<string, string> = {
    py: 'python',
    js: 'javascript',
    ts: 'typescript',
    tsx: 'typescript',
    jsx: 'jsx',
    java: 'java',
    cpp: 'cpp',
    c: 'c',
    cs: 'csharp',
    go: 'go',
    rs: 'rust',
    rb: 'ruby',
    php: 'php',
    swift: 'swift',
    kt: 'kotlin',
    scala: 'scala',
    sql: 'sql',
    sh: 'bash',
    bash: 'bash',
    json: 'json',
    yaml: 'yaml',
    yml: 'yaml',
    xml: 'xml',
    css: 'css',
    scss: 'scss',
    html: 'html',
  };

  return langMap[ext] || 'plaintext';
}

/**
 * Extract plain text from DOCX-like markdown representation
 * (DOCX generated by create_docx tool is actually well-structured markdown)
 */
export function extractDocxText(docxContent: string): string {
  // DOCX tool returns markdown, so we can use it as-is for display
  // Remove any embedded encoding markers if present
  return docxContent
    .replace(/\[Document\]:\s*<>/g, '') // Remove document markers
    .replace(/\[.*?]:\s*<.*?>/g, '') // Remove reference-style link definitions
    .trim();
}

/**
 * Convert HTML to safe displayable content (basic sanitization)
 * For production, consider using DOMPurify
 */
export function sanitizeHtml(html: string): string {
  // Basic sanitization: remove script tags and event handlers
  let sanitized = html
    .replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, '') // Remove script tags
    .replace(/on\w+\s*=\s*["'][^"']*["']/gi, '') // Remove event handlers
    .replace(/on\w+\s*=\s*[^\s>]*/gi, ''); // Remove unquoted event handlers

  return sanitized;
}

/**
 * Extract text from PDF content (if already extracted)
 * This is a placeholder since PDF extraction requires specialized libraries
 */
export function extractPdfText(pdfContent: string): string {
  // In production, use pdfjs-dist to extract text from PDF buffer
  return 'PDF extraction requires additional processing. Please download the PDF to view.';
}

/**
 * Render document content based on type
 */
export interface DocumentContent {
  content: string;
  fileType: 'docx' | 'pdf' | 'md' | 'html' | 'txt' | 'code';
  language?: string;
  isPreview?: boolean; // true if content is preview/excerpt
}

/**
 * Format document for display
 */
export function formatDocument(content: string, fileType: 'docx' | 'pdf' | 'md' | 'html' | 'txt' | 'code', language?: string): DocumentContent {
  let formatted = content;

  switch (fileType) {
    case 'docx':
      // DOCX tool returns markdown, extract clean text
      formatted = extractDocxText(content);
      break;

    case 'pdf':
      // PDF: extract available text
      formatted = extractPdfText(content);
      break;

    case 'html':
      // HTML: sanitize for display
      formatted = sanitizeHtml(content);
      break;

    case 'code':
      // Code: trim excess whitespace but preserve formatting
      formatted = content.trim();
      break;

    case 'md':
    case 'txt':
    default:
      // Markdown and text: use as-is
      formatted = content.trim();
  }

  return {
    content: formatted,
    fileType,
    language: fileType === 'code' ? language || 'plaintext' : undefined,
    isPreview: content.length > 10000, // Mark as preview if truncated
  };
}

/**
 * Generate preview text (first N chars) from content
 */
export function generatePreview(content: string, maxLength: number = 200): string {
  const trimmed = content.trim().replace(/\s+/g, ' ');
  return trimmed.length > maxLength ? `${trimmed.slice(0, maxLength)}...` : trimmed;
}

/**
 * Count words in document
 */
export function countWords(content: string): number {
  return content
    .trim()
    .split(/\s+/)
    .filter(word => word.length > 0).length;
}

/**
 * Estimate reading time (average 200 words/minute)
 */
export function estimateReadingTime(content: string): string {
  const wordCount = countWords(content);
  const minutes = Math.ceil(wordCount / 200);
  return minutes === 1 ? '1 min' : `${minutes} min`;
}

/**
 * Check if content is valid for display
 */
export function isValidContent(content: unknown): boolean {
  return typeof content === 'string' && content.trim().length > 0;
}

/**
 * Get file size formatted string
 */
export function formatFileSize(bytes: number): string {
  if (bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return Math.round((bytes / Math.pow(k, i)) * 100) / 100 + ' ' + sizes[i];
}
